version: '3.7'

services:
  axon:
    image: axoniq/axonserver
    container_name: axonserver
    hostname: axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    networks:
      - axonserver-net
  mysql:
    image: mysql:8.0.16
    container_name: cqrs-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: cqrs_db
    volumes:
      - cqrs-mysql-data:/var/lib/mysql
    networks:
      - axonserver-net

volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config:
  cqrs-mysql-data:

networks:
  axonserver-net: